service: fookie-cloud
frameworkVersion: "2"
provider:
  region: eu-central-1
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
functions:
  fookie:
    handler: default
    events:
      - http:
          path: /api
          method: POST
plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-offline
package:
  patterns:
    - "!node_modules/**" # no need to add this, this plugin does it for you

